### ISSUE TITLE
"Failed to delete" folder

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/NemakiWare#106]
On the demo site, I just tried to delete a folder `myf1` that contains 2 files, and received this error:

![nemakiware-failed-to-delete](https://cloud.githubusercontent.com/assets/99590/6227534/48502228-b6e4-11e4-8335-addd85961cc6.png)

All folders/files created as admin, deletion also attempted as admin.

**Comment by linzhixing** [comment]
This error is reproduced.

The reason is because deleteObject method is called for the purpose of deleteing a folder containing some contents.
In that case, we must use deleteTree method.
It will be soon fixed.

Thanks a lot for reporting a bug :)
