### ISSUE TITLE
Installation problem on Windows with NemakiWareInstaller-2.1.jar

### ISSUE THREAD

**Issue by zuchowski** [aegif/NemakiWare#123]
Hi, I've been trying to install application from NemakiWareInstaller-2.1.jar on Windows 7. 
1. I've chosen ENG version
2. I've changed installation path to: "d:\_PROJECTS_2015\Nemaki\"
3. I've been clicking next to get the default installation and default ports

Installation Path
d:\_PROJECTS_2015\Nemaki
Chosen Installation Packs
Tomcat Core CouchDB initial data import Solr UI Installation utility Delete tmp files

Installation fails on tomcat\solr.xml ( 7/7) with Exception, that it cannot connect to  DB:
![error_nemaki](https://cloud.githubusercontent.com/assets/1155242/7022093/82ddf9f0-dd28-11e4-8560-bdac6f4c1362.png)

After finishing installation Setup catalog with couchdb still exists with files:
```
bjornloka.jar
couchdb_install_centos6.sh
initial_import
setup_couchdb.bat
setup_couchdb.sh
```
When I manually run setup_couchdb.bat I'm getting error that it cannot find POM file:
```
d:\_PROJECTS_2015\Nemaki\setup\couchdb>setup_couchdb.bat

d:\_PROJECTS_2015\Nemaki\setup\couchdb>set EXECUTE_CD=d:\_PROJECTS_2015\Nemaki\setup\couchdb

d:\_PROJECTS_2015\Nemaki\setup\couchdb>cd /d d:\_PROJECTS_2015\Nemaki\setup\couchdb\

d:\_PROJECTS_2015\Nemaki\setup\couchdb>set UTIL_HOME=bjornloka

d:\_PROJECTS_2015\Nemaki\setup\couchdb>mvn -f bjornloka package
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (d:\_PROJECTS_2015\Nemaki\setup\couchdb\bjornloka) has 1 error
[ERROR]     Non-readable POM d:\_PROJECTS_2015\Nemaki\setup\couchdb\bjornloka: d:\_PROJECTS_2015\Nemaki\setup\couchdb\bjornloka (Nie można odnaleźć określonego
pliku)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by linzhixing** [comment]
Thanks for your report!

First, can you check if CouchDB instance ran correctly in your environment?

Second, there rest unnecessary setup files such as setup_couchdb.bat.
What we need here is ```setup/couchdb/bjornloka.jar```.

```java -cp setup/couchdb/bjornloka.jar jp.aegif.nemaki.bjornloka.Load 127.0.0.1 5984 bedroom setup/couchdb/initial_import/bedroom_init.dump```
```java -cp setup/couchdb/bjornloka.jar jp.aegif.nemaki.bjornloka.Load 127.0.0.1 5984 archive setup/couchdb/initial_import/archive_init.dump```

By these commands, initial data is put into CouchDB.

**Comment by zuchowski** [comment]
Thank you, My fault. I did not read Wiki before installing. I didn't have DB started before installation.
