### ISSUE TITLE
ファイルのリスト表示件数を自由に設定したい

### ISSUE THREAD

**Issue by sixpetals** [aegif/NemakiWare#130]
現在既に変更できるとのことですが、Wikiに変更の仕方を書く、を達成したところでクローズとしたいです。

**Comment by linzhixing** [comment]
Wikiに記載しました。
https://github.com/aegif/NemakiWare/wiki/%E7%92%B0%E5%A2%83%E8%A8%AD%E5%AE%9A%28UI%29:-%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3
