### ISSUE TITLE
同名ファイルをD&Dした場合、既存ファイルを上書きしたい

### ISSUE THREAD

**Issue by sixpetals** [aegif/NemakiWare#135]
上書きするか、新規登録するか毎回ダイアログで尋ねる、でもいいとおもいます。

文書名が一致した場合、いわゆるPCのエクスプローラとおなじうごきを期待しているユーザさんは、新規作成でなく上書きという操作を期待するようです。文書管理上は名前も一つのプロパティに過ぎないという考えだとは思いますが、結局（１）とかつけているので上書きもあり得るかなと思います。

**Comment by linzhixing** [comment]
上書きにすること自体は可能ですが、上書きor別名で新規登録を「毎回ダイアログで尋ねる」部分は必要性の高い要望でしょうか？ エクスプローラやFinderと同じなら、上書きにしろ別名で新規登録にしろ、毎回尋ねられることはないと思います。

上書き/別名で新規登録、の切り替え自体、CMISリポジトリ側で実装するかUI側で実装するかの自由度があるのと(できれば前者に寄せたい)、UI側でダイアログを出すとなるとアップロード前にリポジトリと通信して名前を走査するコストを払った上でUI側での実装に倒さざるをえないので、確認しておきたいです。

**Comment by sixpetals** [comment]
いまのところ
・できればUIで完結してほしい
・設定で「毎回聞く・強制的に上書き・強制的にリネームして新規追加」の３つから選べるようにする
を考えています。
