### ISSUE TITLE
ID and Name inversed by creation form

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/NemakiWare#251]
Create a new group like this:

![screenshot from 2016-10-12 14-27-40](https://cloud.githubusercontent.com/assets/99590/19298406/54431d5e-9088-11e6-9f55-c433213c09ba.png)

Result:

![screenshot from 2016-10-12 14-29-07](https://cloud.githubusercontent.com/assets/99590/19298414/5a320e5a-9088-11e6-9b9e-b710f97de069.png)

CMIS Workbench:

![screenshot from 2016-10-12 14-30-20](https://cloud.githubusercontent.com/assets/99590/19298429/7ad470c6-9088-11e6-989c-12ffd974cd47.png)

**Comment by sixpetals** [comment]
fixed. 
commit 2cf7acd2a01335a9261821a77f59e00c9b519a8b
