### ISSUE TITLE
NemakiWare does not start - default installer with Tomcat

### ISSUE THREAD

**Issue by lafar6502** [aegif/NemakiWare#57]
Hi, I'm trying to start NemakiWare from a downloaded installer jar (I have tried ), but can't get the application to run.
The problem appears during start, when loading the 'nemakiware.war' application - it appears that there's a conflict between servlet.api provided by Tomcat (lib/servlet-api.jar) and servlet-api-2.3.jar contained in the nemakiware.war file. I'm using JDK 1.7 on Windows 64 bit. Installer: NemakiWareInstaller-1.1.jar, tried also NemakiWareInstaller-1.1-Win.jar with same results.
Is the distribution broken or am I doing something wrong?

sie 29, 2014 11:28:55 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive C:\tools\NemakiWare2\apache-tomcat-7.0.41\webapps\nemakiware.war
sie 29, 2014 11:28:57 PM org.apache.catalina.loader.WebappClassLoader validateJa
rFile
INFO: validateJarFile(C:\tools\NemakiWare2\apache-tomcat-7.0.41\webapps\nemakiwa
re\WEB-INF\lib\servlet-api-2.3.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/servlet/Servlet.class

**Comment by linzhixing** [comment]
NemakiWare is updated to version 2.0.
Could you please try it again and see if the problem is reproduced?
