### ISSUE TITLE
ユーザ名が文字化けする

### ISSUE THREAD

**Issue by sixpetals** [aegif/NemakiWare#78]
ユーザ名などをマルチバイト文字にすると文字化けします。
新規作成も編集もどちらも文字化けしたままです。

サーバ：Windows 7 
ブラウザ：Chrome 38

![snapcrab_noname_2014-11-18_15-59-32_no-00](https://cloud.githubusercontent.com/assets/2577371/5083575/e88e7fdc-6f3b-11e4-8c1a-59c6b6b2a801.png)

**Comment by linzhixing** [comment]
It was because of Tomcat encoding on Windows environment, and already resolved.
