### ISSUE TITLE
詳細ボタンを押すとエラーになる

### ISSUE THREAD

**Issue by sixpetals** [aegif/NemakiWare#86]
2.0beta4 ですが、WindowsでビルドしたインストーラでWindowsにインストールしました。
ファイルをアップロードして詳細ボタンを押したらこんなエラーが出ます。

![snapcrab_noname_2014-12-22_18-30-57_no-00](https://cloud.githubusercontent.com/assets/2577371/5523228/fcf5d032-8a08-11e4-99be-d5c1e3dbe021.png)

ちなみにフォルダの詳細でも同じエラー。プロパティの表示が壊れてるっぽいです。
ブラウザはChromeでもFirefoxでも起きます。

**Comment by linzhixing** [comment]
コミット7a0f889a13c519d8b5cc6dd4455c968ad43fdf3bでfixed
